name: solosync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  http: ^1.2.1
  pinput: ^5.0.0
  intl: ^0.19.0
  calendar_date_picker2: ^1.1.2
  toggle_switch: 2.3.0
  fl_chart: ^0.68.0
  flutter_charts: ^0.5.2
  grouped_list: ^5.1.2
  sms_autofill: ^2.3.1
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^25.2.7
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.8
  iconify_flutter: ^0.0.5
  provider: ^6.1.2
#  flutter_form_builder: ^9.3.0
  app_settings: ^5.1.1
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.13.1
  introduction_screen: ^3.1.14
  animate_do: ^3.3.4
  line_awesome_flutter: ^3.0.1

  razorpay_web: ^1.4.2


  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^3.0.2
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/google-icon.png
    - assets/icons/default.png
    - assets/logo/solosync.png
    - assets/icons/tasks.png
    - assets/icons/meetings.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/solosync.png"
