name: solosync
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.19.0
  calendar_date_picker2: ^0.5.5
  toggle_switch: 2.1.0
  fl_chart: ^0.66.2
  flutter_charts: ^0.5.2
  grouped_list: ^5.1.2
  sms_autofill: ^2.3.1
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^24.2.9
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.6
  iconify_flutter: ^0.0.5
  provider: ^6.1.2

  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
#  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^2.0.1


  flutter_lints: ^3.0.1

flutter:


  uses-material-design: true

  assets:
    - assets/icons/google-icon.png

